In [1]:
%pwd

'C:\\NN-P4\\python-notebooks'

###Imports and Read CSV

In [2]:
import json
import numpy as np
import pandas as pd
import tensorflow as tf
import os
from datetime import datetime
from keras.callbacks import History # to get train accuracy
history = History()

In [3]:
#nPrintML creates a copy of dataset in pkl picles format. Convert to CSV 1st.
# Read the PKL
# df_train = pd.read_pickle('../datasets/nprint-raw/country-of-origin/X.pkl')
# df_test = pd.read_pickle('../datasets/nprint-raw/country-of-origin/X_val.pkl')
# label_train = pd.read_pickle('../datasets/nprint-raw/country-of-origin/y.pkl')
# label_test = pd.read_pickle('../datasets/nprint-raw/country-of-origin/y_val.pkl')
# # Save a copy as CSV
# df_train.to_csv('../datasets/nprint-raw/country-of-origin/X.csv')
# df_test.to_csv('../datasets/nprint-raw/country-of-origin/X_val.csv')
# label_train.to_csv('../datasets/nprint-raw/country-of-origin/y.csv')
# label_test.to_csv('../datasets/nprint-raw/country-of-origin/y_val.csv')
# Read CSV
df_train = pd.read_csv('../datasets/nprint-raw/country-of-origin/X.csv')
df_test = pd.read_csv('../datasets/nprint-raw/country-of-origin/X_val.csv')
label_train = pd.read_csv('../datasets/nprint-raw/country-of-origin/y.csv')
label_test = pd.read_csv('../datasets/nprint-raw/country-of-origin/y_val.csv')
#Drop colum with pcap sequence number
df_train.drop('pcap', axis=1, inplace=True)
df_test.drop('pcap', axis=1, inplace=True)
label_train.drop('pcap', axis=1, inplace=True)
label_test.drop('pcap', axis=1, inplace=True)
#Rename Unnamed Collumn
label_train.rename(columns={'0': 'label'}, inplace=True)
label_test.rename(columns={'0': 'label'}, inplace=True)
#Read file with ordered list of attributes ranked by the autoML feature importance algorithm
features_rankings_df = pd.read_csv('../datasets/nprint-raw/country-of-origin/feature-importance.csv')
features_rankings_df.rename(columns={'0': 'label'}, inplace=True)

In [4]:
display(df_train)
display(df_test)
display(label_train)
display(label_test)
print(label_train["label"].value_counts())
print(label_test["label"].value_counts())
print(f"df_train shape: {df_train.shape} \n columns: {df_train.columns.values}")
print(f"df_test shape: {df_test.shape} \n columns: {df_test.columns.values}")
display(features_rankings_df.head(40))

pkt_0_ipv4_tos_6  pkt_0_ipv4_tl_6  pkt_0_ipv4_tl_7  pkt_0_ipv4_tl_8  \
0                   0                0                0                0   
1                   0                0                0                0   
2                   0                0                0                0   
3                   0                0                0                0   
4                   0                0                0                0   
..                ...              ...              ...              ...   
232                 0                0                0                0   
233                 0                0                0                0   
234                 0                0                0                0   
235                 0                0                0                0   
236                 0                1                0                0   

     pkt_0_ipv4_tl_9  pkt_0_ipv4_tl_10  pkt_0_ipv4_tl_11  pkt_0_ipv4_tl_12  \
0                  0                 1                 1                 1   
1                  1                 0                 0                 0   
2                  1                 0                 0                 0   
3                  1                 0                 0                 0   
4                  1                 0                 0                 0   
..               ...               ...               ...               ...   
232                1                 0                 0                 0   
233                1                 0                 0                 0   
234                0                 1                 1                 1   
235                1                 0                 0                 0   
236                0                 0                 1                 0   

     pkt_0_ipv4_tl_13  pkt_0_ipv4_tl_14  ...  pkt_9_udp_cksum_6  \
0                   1                 1  ...                 -1   
1                   0                 1  ...                 -1   
2                   0                 0  ...                  1   
3                   0                 1  ...                 -1   
4                   0                 1  ...                 -1   
..                ...               ...  ...                ...   
232                 0                 0  ...                 -1   
233                 0                 0  ...                  0   
234                 1                 1  ...                 -1   
235                 1                 1  ...                 -1   
236                 1                 0  ...                 -1   

     pkt_9_udp_cksum_7  pkt_9_udp_cksum_8  pkt_9_udp_cksum_9  \
0                   -1                 -1                 -1   
1                   -1                 -1                 -1   
2                    1                  1                  1   
3                   -1                 -1                 -1   
4                   -1                 -1                 -1   
..                 ...                ...                ...   
232                 -1                 -1                 -1   
233                  0                  0                  0   
234                 -1                 -1                 -1   
235                 -1                 -1                 -1   
236                 -1                 -1                 -1   

     pkt_9_udp_cksum_10  pkt_9_udp_cksum_11  pkt_9_udp_cksum_12  \
0                    -1                  -1                  -1   
1                    -1                  -1                  -1   
2                     1                   0                   0   
3                    -1                  -1                  -1   
4                    -1                  -1                  -1   
..                  ...                 ...                 ...   
232                  -1                  -1                  -1   
233                   0                   0  

pkt_0_ipv4_tos_6  pkt_0_ipv4_tl_6  pkt_0_ipv4_tl_7  pkt_0_ipv4_tl_8  \
0                  0                0                0                0   
1                  0                0                0                0   
2                  0                0                0                0   
3                  0                0                0                0   
4                  0                0                0                0   
5                  0                0                0                0   
6                  0                0                0                0   
7                  0                0                0                0   
8                  0                0                0                0   
9                  0                0                0                0   
10                 0                0                0                0   
11                 0                0                0                0   
12                 0                0                0                0   
13                 0                0                0                0   
14                 0                0                0                0   
15                 0                0                0                0   
16                 0                0                0                0   
17                 0                0                0                0   
18                 0                0                0                0   
19                 0                0                0                0   
20                 0                0                0                0   
21                 0                0                0                1   
22                 0                0                0                0   
23                 0                0                0                0   
24                 0                0                0                0   
25                 0                0                0                0   
26                 0                0                0                0   
27                 0                0                0                0   
28                 0                0                0                0   
29                 0                0                0                0   
30                 0                0                0                0   
31                 0                0                0                0   
32                 0                0                0                0   
33                 0                0                0                0   
34                 0                0                0                0   
35                 0                0                0                0   
36                 0                0                0                0   
37                 0                0                0                0   
38                 0                0                0                0   
39                 0                0                0                0   
40                 0                0                0                0   
41                 0                0                0                0   
42                 0                0                0                1   
43                 0                0                0                0   
44                 0                0                0                0   
45                 0                0                0                0   
46                 0                0                0                1   
47                 0                0                0                0   
48                 0                0                0                0   
49                 0                0                0                0   
50                 0                0                0                1   
51                 0                0                0                0   
52                 0         

label
0        0
1        0
2        1
3        0
4        1
..     ...
232      1
233      2
234      1
235      2
236      2

[237 rows x 1 columns]

label
0       2
1       1
2       2
3       2
4       2
5       2
6       2
7       2
8       1
9       1
10      0
11      0
12      0
13      0
14      1
15      1
16      2
17      1
18      1
19      1
20      2
21      1
22      1
23      0
24      1
25      0
26      2
27      2
28      0
29      0
30      1
31      1
32      0
33      0
34      2
35      2
36      1
37      0
38      0
39      2
40      0
41      2
42      1
43      0
44      1
45      2
46      1
47      1
48      1
49      1
50      1
51      0
52      2
53      2
54      0
55      1
56      0
57      1
58      0
59      1

label
1    97
0    70
2    70
Name: count, dtype: int64
label
1    24
2    18
0    18
Name: count, dtype: int64
df_train shape: (237, 4825) 
 columns: ['pkt_0_ipv4_tos_6' 'pkt_0_ipv4_tl_6' 'pkt_0_ipv4_tl_7' ...
 'pkt_9_udp_cksum_13' 'pkt_9_udp_cksum_14' 'pkt_9_udp_cksum_15']
df_test shape: (60, 4825) 
 columns: ['pkt_0_ipv4_tos_6' 'pkt_0_ipv4_tl_6' 'pkt_0_ipv4_tl_7' ...
 'pkt_9_udp_cksum_13' 'pkt_9_udp_cksum_14' 'pkt_9_udp_cksum_15']


Unnamed: 0  importance    stddev       p_value   n  p99_high  \
0      pkt_5_tcp_opt_64    0.100000  0.017568  1.147362e-08  10  0.118055   
1      pkt_9_tcp_opt_64    0.075000  0.014164  2.161733e-08  10  0.089556   
2      pkt_5_tcp_opt_65    0.066667  0.017568  3.849943e-07  10  0.084721   
3      pkt_8_tcp_opt_64    0.058333  0.011785  3.894775e-08  10  0.070445   
4      pkt_7_tcp_opt_64    0.058333  0.014164  1.911429e-07  10  0.072889   
5      pkt_7_tcp_opt_65    0.055000  0.017656  2.027185e-06  10  0.073145   
6      pkt_3_tcp_opt_64    0.053333  0.013147  2.175770e-07  10  0.066844   
7      pkt_3_ipv4_ttl_6    0.048333  0.018342  7.977694e-06  10  0.067183   
8      pkt_6_tcp_opt_64    0.046667  0.010541  1.025415e-07  10  0.057499   
9     pkt_8_tcp_sprt_14    0.041667  0.018002  2.235802e-05  10  0.060167   
10     pkt_9_tcp_opt_95    0.038333  0.017656  3.671296e-05  10  0.056478   
11   pkt_8_ipv4_cksum_1    0.038333  0.015811  1.552399e-05  10  0.054583   
12     pkt_4_tcp_opt_64    0.038333  0.011249  9.572658e-07  10  0.049894   
13     pkt_6_tcp_opt_65    0.038333  0.017656  3.671296e-05  10  0.056478   
14     pkt_8_tcp_opt_65    0.036667  0.013147  5.036448e-06  10  0.050178   
15     pkt_0_ipv4_tl_11    0.036667  0.015316  1.714780e-05  10  0.052406   
16    pkt_9_tcp_dprt_15    0.035000  0.009461  4.779303e-07  10  0.044723   
17     pkt_0_ipv4_ttl_7    0.035000  0.012298  4.269026e-06  10  0.047638   
18   pkt_5_udp_dport_10    0.033333  0.007857  1.480476e-07  10  0.041408   
19     pkt_8_tcp_ackf_0    0.033333  0.017568  1.012497e-04  10  0.051388   
20     pkt_1_ipv4_tl_12    0.031667  0.009461  1.112764e-06  10  0.041389   
21     pkt_9_tcp_opt_33    0.031667  0.009461  1.112764e-06  10  0.041389   
22   pkt_8_tcp_wsize_12    0.031667  0.018342  2.003147e-04  10  0.050516   
23   pkt_6_ipv4_cksum_4    0.028333  0.020861  1.002689e-03  10  0.049772   
24   pkt_5_ipv4_cksum_6    0.028333  0.011249  1.146336e-05  10  0.039894   
25    pkt_9_tcp_dprt_10    0.028333  0.019325  6.127819e-04  10  0.048193   
26   pkt_1_udp_sport_13    0.028333  0.017656  3.338084e-04  10  0.046478   
27     pkt_8_tcp_seq_16    0.028333  0.013721  5.382514e-05  10  0.042434   
28     pkt_2_ipv4_id_13    0.026667  0.014055  1.012497e-04  10  0.041110   
29    pkt_1_udp_cksum_6    0.026667  0.019563  9.800872e-04  10  0.046771   
30     pkt_0_ipv4_tl_12    0.026667  0.011653  2.443998e-05  10  0.038643   
31    pkt_6_udp_cksum_9    0.025000  0.014164  1.711320e-04  10  0.039556   
32     pkt_4_ipv4_ttl_4    0.025000  0.014164  1.711320e-04  10  0.039556   
33     pkt_9_tcp_opt_65    0.025000  0.011785  4.385699e-05  10  0.037111   
34   pkt_3_ipv4_cksum_4    0.025000  0.014164  1.711320e-04  10  0.039556   
35     pkt_9_ipv4_id_14    0.023333  0.011653  6.788833e-05  10  0.035309   
36  pkt_4_ipv4_cksum_14    0.023333  0.016102  6.614753e-04  10  0.039881   
37     pkt_5_ipv4_ttl_1    0.023333  0.011653  6.788833e-05  10  0.035309   
38     pkt_0_udp_len_11    0.023333  0.008607  6.340924e-06  10  0.032178   
39   pkt_2_tcp_wsize_14    0.021667  0.013721  3.728090e-04  10  0.035768   

     p99_low  
0   0.081945  
1   0.060444  
2   0.048612  
3   0.046222  
4   0.043777  
5   0.036855  
6   0.039822  
7   0.029484  
8   0.035834  
9   0.023166  
10  0.020189  
11  0.022084  
12  0.026773  
13  0.020189  
14  0.023156  
15  0.020927  
16  0.025277  
17  0.022362  
18  0.025259  
19  0.015279  
20  0.021944  
21  0.021944  
22  0.012817  
23  0.006895  
24  0.016773  
25  0.008473  
26  0.010189  
27  0.014232  
28  0.012223  
29  0.006562  
30  0.014691  
31  0.010444  
32  0.010444  
33  0.012889  
34  0.010444  
35  0.011357  
36  0.006786  
37  0.011357  
38  0.014488  
39  0.007566

In [5]:
#make a list with only the best features

feature_list = features_rankings_df['Unnamed: 0'].tolist()
feature_list = feature_list[:32]
print(feature_list)

#select a sub-dataframe with only the 32 top attrs rate by the AUTOGLUON feature importance algorithm
df_train = df_train[feature_list]
df_test = df_test[feature_list]

display(df_train)
display(df_test)

['pkt_5_tcp_opt_64', 'pkt_9_tcp_opt_64', 'pkt_5_tcp_opt_65', 'pkt_8_tcp_opt_64', 'pkt_7_tcp_opt_64', 'pkt_7_tcp_opt_65', 'pkt_3_tcp_opt_64', 'pkt_3_ipv4_ttl_6', 'pkt_6_tcp_opt_64', 'pkt_8_tcp_sprt_14', 'pkt_9_tcp_opt_95', 'pkt_8_ipv4_cksum_1', 'pkt_4_tcp_opt_64', 'pkt_6_tcp_opt_65', 'pkt_8_tcp_opt_65', 'pkt_0_ipv4_tl_11', 'pkt_9_tcp_dprt_15', 'pkt_0_ipv4_ttl_7', 'pkt_5_udp_dport_10', 'pkt_8_tcp_ackf_0', 'pkt_1_ipv4_tl_12', 'pkt_9_tcp_opt_33', 'pkt_8_tcp_wsize_12', 'pkt_6_ipv4_cksum_4', 'pkt_5_ipv4_cksum_6', 'pkt_9_tcp_dprt_10', 'pkt_1_udp_sport_13', 'pkt_8_tcp_seq_16', 'pkt_2_ipv4_id_13', 'pkt_1_udp_cksum_6', 'pkt_0_ipv4_tl_12', 'pkt_6_udp_cksum_9']


pkt_5_tcp_opt_64  pkt_9_tcp_opt_64  pkt_5_tcp_opt_65  pkt_8_tcp_opt_64  \
0                   1                 0                 0                 0   
1                   0                 1                 0                -1   
2                  -1                -1                -1                -1   
3                   1                 0                 0                 1   
4                   0                 0                 0                 0   
..                ...               ...               ...               ...   
232                 0                 0                 0                 0   
233                -1                -1                -1                -1   
234                 0                 0                 1                 0   
235                -1                 1                -1                 1   
236                -1                 1                -1                 1   

     pkt_7_tcp_opt_64  pkt_7_tcp_opt_65  pkt_3_tcp_opt_64  pkt_3_ipv4_ttl_6  \
0                   0                 0                 0                 1   
1                  -1                -1                -1                 1   
2                  -1                -1                -1                 1   
3                   1                 0                -1                 1   
4                   0                 0                -1                 0   
..                ...               ...               ...               ...   
232                 0                 0                 0                 0   
233                 1                 1                -1                 1   
234                -1                -1                 0                 1   
235                 0                 0                 0                 1   
236                 1                 1                -1                 1   

     pkt_6_tcp_opt_64  pkt_8_tcp_sprt_14  ...  pkt_8_tcp_wsize_12  \
0                   1                  1  ...                   1   
1                   1                 -1  ...                  -1   
2                  -1                 -1  ...                  -1   
3                  -1                  0  ...                   1   
4                   0                  1  ...                   1   
..                ...                ...  ...                 ...   
232                 0                  1  ...                   1   
233                 0                 -1  ...                  -1   
234                 0                  0  ...                   1   
235                 1                  1  ...                   1   
236                 0                  1  ...                   1   

     pkt_6_ipv4_cksum_4  pkt_5_ipv4_cksum_6  pkt_9_tcp_dprt_10  \
0                     0                   1                  0   
1                     1                   0                  1   
2                     1                   0                 -1   
3                     0                   1                  0   
4                     0                   0                  1   
..                  ...                 ...                ...   
232                   1                   0                  0   
233                   0                   1                 -1   
234                   0                   0                  1   
235                   1                   0                  1   
236                   0                   1                  1   

     pkt_1_udp_sport_13  pkt_8_tcp_seq_16  pkt_2_ipv4_id_13  \
0                     0                 1                 0   
1                    -1                -1                 1   
2                     0                -1                 1   
3                     1                 0                 0   
4                    -1                 1                 0   
..                  ...               ...               ...   
232                   1                 1   

pkt_5_tcp_opt_64  pkt_9_tcp_opt_64  pkt_5_tcp_opt_65  pkt_8_tcp_opt_64  \
0                  1                 1                 0                 0   
1                 -1                -1                -1                -1   
2                 -1                -1                -1                -1   
3                  1                -1                 1                 0   
4                  0                 0                 0                 1   
5                  1                 0                 0                 0   
6                  0                 0                 0                 1   
7                  1                -1                 1                -1   
8                  0                -1                 0                 0   
9                  0                 0                 0                 0   
10                -1                 1                -1                -1   
11                -1                -1                -1                 0   
12                 1                 0                 0                 1   
13                 0                -1                 0                -1   
14                 0                 0                 0                 0   
15                 0                 0                 0                -1   
16                 1                -1                 1                -1   
17                 0                -1                 0                 0   
18                 0                 0                 1                 0   
19                -1                -1                -1                -1   
20                 1                 0                 1                 0   
21                 0                 0                 1                 0   
22                 0                 0                 0                 0   
23                -1                -1                -1                -1   
24                -1                 0                -1                 0   
25                -1                 0                -1                -1   
26                 0                 1                 0                 1   
27                -1                -1                -1                 1   
28                 0                 0                 0                 1   
29                -1                 0                -1                 1   
30                -1                -1                -1                -1   
31                -1                -1                -1                -1   
32                 1                 0                 0                 0   
33                -1                 0                -1                -1   
34                -1                -1                -1                -1   
35                 1                 0                 1                 1   
36                 0                 0                 0                 0   
37                 1                 1                 0                 1   
38                -1                 1                -1                 0   
39                 1                 1                 1                 1   
40                -1                 1                -1                 1   
41                 1                 0                 1                 0   
42                -1                -1                -1                 0   
43                -1                 1                -1                 1   
44                 0                -1                 0                 0   
45                 1                 0                 1                 0   
46                 0                 0                 0                 0   
47                 0                 0                 1                 0   
48                 0                 0                 1                 0   
49                -1                 0                -1                -1   
50                 0      

In [14]:
# Model Parameters
number_of_attributes = df_train.shape[1]
hidden_layer_nodes = 32
output_layer_nodes = 3

# Traing Parameters
EPOCHS = 250
BATCH_SIZE = 250

# Run the NN Training multiple times to get a nice mean score of accuracy results
NUMBER_OF_NN_REPETITIONS = 10

def get_basic_model():
  model = tf.keras.Sequential([
    normalizer,
    tf.keras.layers.Dense(hidden_layer_nodes, activation='relu'),
    tf.keras.layers.Dense(output_layer_nodes)
  ])
  model.compile(optimizer='adam',
                loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                metrics=['accuracy'])
  return model

In [15]:
# Convert int values to TF expect values (float)
df_train = np.asarray(df_train).astype(np.float32)
df_test = np.asarray(df_test).astype(np.float32)
# Converts pandas dataframe to tensorflow object
df_train = tf.convert_to_tensor(df_train)
# Set the 
normalizer = tf.keras.layers.Normalization(axis=-1)
# Normalize the data
normalizer.adapt(df_train)
#normalizer.adapt(numeric_features_test)

In [16]:
# Execute Trainning and Testing
#model = get_basic_model()
train_accuracy = []
test_accuracy = []

for i in range(NUMBER_OF_NN_REPETITIONS):
  model = get_basic_model()
  history = model.fit(df_train, label_train, epochs=EPOCHS, verbose=0, batch_size=BATCH_SIZE, callbacks=[history])
  one_train_accuracy = history.history['accuracy']

  test_loss, one_test_accuracy =  model.evaluate(df_test,  label_test, verbose=1, batch_size=BATCH_SIZE)
  train_accuracy.append(one_train_accuracy[-1])
  test_accuracy.append(one_test_accuracy)
  print(f"{i+1}: train_accuracy:{train_accuracy} test_accuracy:{test_accuracy}")
  tf_predictions_probabilities = model.predict(df_test)
  #tf_loss, tf_acc =  model.evaluate(numeric_features_test,  label_test, verbose=2, batch_size=BATCH_SIZE)

  #Confusion Matrix
  tf_predictions = []
  for i,x in enumerate(tf_predictions_probabilities):
    #print("i:",i,"x_max:",x.max(),"x:",x)
    j_max = x.argmax()
    tf_predictions.append(j_max)
  conf_m = tf.math.confusion_matrix(label_test,tf_predictions)
  print(conf_m)

#After n repetitions of training and testing, calculate statistics
train_accuracy_mean = sum(train_accuracy) / len(train_accuracy)
train_max = max(train_accuracy)
train_min = min(train_accuracy)
train_std = np.std(train_accuracy)
test_accuracy_mean = sum(test_accuracy) / len(test_accuracy)
test_max = max(test_accuracy)
test_min = min(test_accuracy)
test_std = np.std(test_accuracy)

print(f'accuracies_train: {train_accuracy}, accuracies_test: {test_accuracy}')
print(f'train_accuracy_mean: {train_accuracy_mean*100:.2f}, train_max: {train_max*100:.2f}, train_min: {train_min*100:.2f}, train_std: {train_std*100:.2f} \n test_accuracy_mean: {test_accuracy_mean*100:.2f}, test_max: {test_max*100:.2f}, test_min: {test_min*100:.2f}, test_std: {test_std*100:.2f}')



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.7500 - loss: 0.6151
1: train_accuracy:[0.9873417615890503] test_accuracy:[0.75]
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
tf.Tensor(
[[ 7  4  7]
 [ 0 24  0]
 [ 2  2 14]], shape=(3, 3), dtype=int32)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.8000 - loss: 0.5575
2: train_accuracy:[0.9873417615890503, 0.9789029359817505] test_accuracy:[0.75, 0.800000011920929]
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
tf.Tensor(
[[11  4  3]
 [ 0 23  1]
 [ 2  2 14]], shape=(3, 3), dtype=int32)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.7333 - loss: 0.6151
3: train_accuracy:[0.9873417615890503, 0.9789029359817505, 0.9620253443717957] test_accuracy:[0.75, 0.800000011920929, 0.7333333492279053]
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
tf.Tensor(
[[ 9  3  6]
 [ 0 21  3]
 [ 2  2 14]], shape=(3, 3), dtype=int32)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.7333 - loss: 0.5786
4: train_accuracy:[0.9873417615890503, 0.9789029359817505, 0.96202534437

In [13]:
# Date for report file
now = datetime.now()
dt_string = now.strftime("%d-%m-%Y-%H-%M-%S")
print(dt_string)
# Report file content
report = {
    "datetime": dt_string,
    "training_dataset_shape":  str(df_train.shape),
    "test_dataset_shape": str(df_test.shape),
    "number_of_attributes": number_of_attributes,
    "n_epoch":EPOCHS,
    "accuracy_train": train_accuracy_mean,
    "train_max": train_max,
    "train_min": train_min,
    "train_std": train_std,
    "accuracy_test": test_accuracy_mean,
    "test_max": test_max,
    "test_min": test_min,
    "test_std": test_std,
    "accuracies_train": train_accuracy,
    "accuracies_test": test_accuracy
}

# Writes into the file
os.chdir('../tf-model-testing')
print(os.getcwd())

title_parameters_save = f"nn-nprint-app-iden-model-evaluation-{number_of_attributes}x{hidden_layer_nodes}x{output_layer_nodes}.json"
with open(title_parameters_save, "w") as f:
  json.dump(report, f)

title_parameters_save = f"nn-nprint-app-iden-model-evaluation-{number_of_attributes}x{hidden_layer_nodes}x{output_layer_nodes}-{dt_string}.json"
with open(title_parameters_save, "w") as f:
  json.dump(report, f)

24-06-2024-15-36-22
C:\NN-P4\tf-model-testing
