Linkar o Drive com o Google Colab

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
#from __future__ import absolute_import, division, print_function, unicode_literals
from copy import deepcopy
import os
import numpy as np
import pandas as pd
import tensorflow as tf
import sys 
import time

BATCH_SIZE = 2

print(tf.__version__)

2.7.0


Import the data from csv files

In [3]:
path_training ="/content/drive/MyDrive/IC-Colab-CSV files/entry01short3.csv"
path_test ="/content/drive/MyDrive/IC-Colab-CSV files/entry02short3.csv"
training_set = pd.read_csv(path_training, header=None, skiprows=1, dtype=np.float32)
df = pd.read_csv(path_training, header=None, skiprows=1, dtype=np.float32)
test_set = pd.read_csv(path_test, header=None, skiprows=1, dtype=np.float32)

training_set
#training_set.describe
#test_set.describe


0    1    2       3       4    5     6
0      80.0  0.0  1.0  1380.0   140.0  0.0  14.0
1      80.0  0.0  1.0  1380.0   141.0  0.0  14.0
2      80.0  0.0  1.0  1380.0   141.0  0.0  14.0
3      80.0  0.0  1.0  1380.0   142.0  0.0  14.0
4      80.0  0.0  1.0  1380.0   141.0  0.0  14.0
...     ...  ...  ...     ...     ...  ...   ...
24858  25.0  0.0  4.0  1460.0    42.0  0.0  14.0
24859  25.0  0.0  7.0  1460.0    65.0  0.0  14.0
24860  25.0  0.0  7.0  1460.0    42.0  0.0  14.0
24861  80.0  0.0  1.0  1460.0  1608.0  0.0  14.0
24862  25.0  0.0  4.0  1460.0    42.0  0.0  14.0

[24863 rows x 7 columns]

Pre-process the data:
  Define the min value and scale for each column

In [4]:
min1 = np.min(training_set)
scale1 = np.max(training_set)-np.min(training_set)
ports = np.array([  80,   25,  443,   21, 3306,   53,  110,  135, 2234, 4662,  143, 6346, 8765], dtype=np.float32) 

#Minimun and scale values for the test set were not defined in the original Script
min2 = np.min(test_set)
scale2 = np.max(test_set)-np.min(test_set)

#print(min1)
#print("\n")
#print(scale1)
#print("\n")
#print(ports)

Pre-Process the data

  

In [5]:
j, k =training_set.shape
train1 = deepcopy(training_set)
print(j)
print(k)
print("\n")
for i in range(0,k):
  for l in range(0,j):
    train1.iloc[l][i] = train1.iloc[l][i]-min1[i]
    train1.iloc[l][i] = (train1.iloc[l][i])/(scale1[i])
    #  normalize the data by subtracting the minimun values and dividing by the scale
print(train1)
print("\n")
switch = np.zeros((j,13))
#print(switch)
#print("\n")
for i in range(0,j):
  for l in range(0,13):
    #print(l)
    #print("\n")
    if training_set.loc[i][0] == ports[l]:
      # The switch matrice map up the ports
      switch[i][l]=1 
      break
print('switch')
print(switch)
print("\n")
#train2 = np.concatenate((switch,train1[:,1:k]),1) o que isso está fazendo
#print('train2')
#print(train2)
#print("\n")
#x = tf.constant(train2)
#y = tf.constant(test_set.target)

24863
7


              0    1         2         3         4    5    6
0      0.001245  0.0  0.001351  0.168457  0.026252  0.0  0.7
1      0.001245  0.0  0.001351  0.168457  0.026439  0.0  0.7
2      0.001245  0.0  0.001351  0.168457  0.026439  0.0  0.7
3      0.001245  0.0  0.001351  0.168457  0.026627  0.0  0.7
4      0.001245  0.0  0.001351  0.168457  0.026439  0.0  0.7
...         ...  ...       ...       ...       ...  ...  ...
24858  0.000389  0.0  0.005405  0.178223  0.007875  0.0  0.7
24859  0.000389  0.0  0.009459  0.178223  0.012188  0.0  0.7
24860  0.000389  0.0  0.009459  0.178223  0.007875  0.0  0.7
24861  0.001245  0.0  0.001351  0.178223  0.301519  0.0  0.7
24862  0.000389  0.0  0.005405  0.178223  0.007875  0.0  0.7

[24863 rows x 7 columns]


switch
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]




Another way of doing things, using tensorflow normalization


In [6]:
numeric_feature_names = [0 ,1, 2, 3, 4, 5, 6]
numeric_features = df[numeric_feature_names]
#numeric_features.head()

tf.convert_to_tensor(numeric_features)

normalizer = tf.keras.layers.Normalization(axis=-1)
normalizer.adapt(numeric_features)

normalizer(numeric_features.iloc[:])

<tf.Tensor: shape=(24863, 7), dtype=float32, numpy=
array([[-0.17237256, -0.04842299, -0.17974274, ..., -0.57019943,
        -0.15029833, -0.04123238],
       [-0.17237256, -0.04842299, -0.17974274, ..., -0.5693457 ,
        -0.15029833, -0.04123238],
       [-0.17237256, -0.04842299, -0.17974274, ..., -0.5693457 ,
        -0.15029833, -0.04123238],
       ...,
       [-0.18075933, -0.04842299,  0.03891247, ..., -0.6538648 ,
        -0.15029833, -0.04123238],
       [-0.17237256, -0.04842299, -0.17974274, ...,  0.68307406,
        -0.15029833, -0.04123238],
       [-0.18075933, -0.04842299, -0.07041513, ..., -0.6538648 ,
        -0.15029833, -0.04123238]], dtype=float32)>

In [7]:
def get_basic_model():
  model = tf.keras.Sequential([
    normalizer,
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1)
  ])

  model.compile(optimizer='adam',
                loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                metrics=['accuracy'])
  return model

In [8]:
model = get_basic_model()
model.fit(numeric_features, target, epochs=10, batch_size=BATCH_SIZE)

NameError: ignored